# ah
name: AH_Bot

# basic
verbose: true
silent: false

# input
data: ['items.csv']

# output
stub: items
overwrite: true
backup: true

# sql
hostname: 127.0.0.1
database: tpzdb
username: root
password: flames
fail: true

# broker
restock: 3600
tick: 30

# scrub
itemids: []
stock01: 12
stock12: 12
urls: []
